### ISSUE TITLE
non-unique choice names

### ISSUE THREAD

**Issue by mabafaba** [boukepieter/MCNA_Analysys_Iraq#8]
Noticed that this choice name appears multiple times: "al.mahmoudiya"
I know they're on different filters but it's gonna cause us trouble I believe - could we change?

**Comment by mabafaba** [comment]
ideally change the label too!

**Comment by boukepieter** [comment]
Yes, I saw that before as well. Technically it shouldn't be a problem because the sample is only in one of them, but it might be better to fix it anyway indeed. I'll have a look at it.

**Comment by mabafaba** [comment]
it's only these:

```
        list_name          name         label label::Arabic filter
43  district_mcna al.mahmoudiya Al Mahmoudiya               basrah
73  district_mcna al.mahmoudiya Al Mahmoudiya               missan
81  district_mcna al.mahmoudiya Al Mahmoudiya                najaf
```

worried this will cause issues when operating on the labeled dataset; they can't be made unique so any spreading / gathering is in DANGERRR

**Comment by boukepieter** [comment]
There is just a new administrative boundaries shape published in which this issue is solved. The names are unique now :). I just have to implement the new names in the kobo tool and ID list and it should work fine.

**Comment by boukepieter** [comment]
link to the new boundaries: https://data.humdata.org/dataset/iraq-admin-level-1-boundaries
